class AppConstants {
  static const String appName = 'Nibangsh Consultancy';
  static const String appTagline = 'Your Gateway to Global Education';

  // Nepal Provinces
  static const List<String> provinces = [
    'Koshi Province',
    'Madhesh Province',
    'Bagmati Province',
    'Gandaki Province',
    'Lumbini Province',
    'Karnali Province',
    'Sudurpashchim Province',
  ];

  static const Map<String, String> provinceValues = {
    'Koshi Province': 'koshi',
    'Madhesh Province': 'madhesh',
    'Bagmati Province': 'bagmati',
    'Gandaki Province': 'gandaki',
    'Lumbini Province': 'lumbini',
    'Karnali Province': 'karnali',
    'Sudurpashchim Province': 'sudurpashchim',
  };

  // Nepal Districts (common ones)
  static const List<String> districts = [
    'Achham',
    'Arghakhanchi',
    'Baglung',
    'Baitadi',
    'Bajhang',
    'Bajura',
    'Banke',
    'Bara',
    'Bardiya',
    'Bhaktapur',
    'Bhojpur',
    'Chitwan',
    'Dadeldhura',
    'Dailekh',
    'Dang',
    'Darchula',
    'Dhading',
    'Dhankuta',
    'Dhanusha',
    'Dolakha',
    'Dolpa',
    'Doti',
    'Gorkha',
    'Gulmi',
    'Humla',
    'Ilam',
    'Jajarkot',
    'Jhapa',
    'Jumla',
    'Kailali',
    'Kalikot',
    'Kanchanpur',
    'Kapilvastu',
    'Kaski',
    'Kathmandu',
    'Kavrepalanchok',
    'Khotang',
    'Lalitpur',
    'Lamjung',
    'Mahottari',
    'Makwanpur',
    'Manang',
    'Morang',
    'Mugu',
    'Mustang',
    'Myagdi',
    'Nawalpur',
    'Nuwakot',
    'Okhaldhunga',
    'Palpa',
    'Panchthar',
    'Parasi',
    'Parbat',
    'Parsa',
    'Pyuthan',
    'Ramechhap',
    'Rasuwa',
    'Rautahat',
    'Rolpa',
    'Rukum East',
    'Rukum West',
    'Rupandehi',
    'Salyan',
    'Sankhuwasabha',
    'Saptari',
    'Sarlahi',
    'Sindhuli',
    'Sindhupalchok',
    'Siraha',
    'Solukhumbu',
    'Sunsari',
    'Surkhet',
    'Syangja',
    'Tanahun',
    'Taplejung',
    'Tehrathum',
    'Udayapur',
    'Chitwan',
    'Butwal',
    'Biratnagar',
    'Birgunj',
    'Dharan',
    'Hetauda',
    'Nepalgunj',
    'Dhangadhi',
    'Itahari',
    'Janakpur',
    'Bharatpur',
  ];

  static const Map<String, String> districtValues = {
    // Koshi
    'Bhojpur': 'bhojpur',
    'Dhankuta': 'dhankuta',
    'Ilam': 'ilam',
    'Jhapa': 'jhapa',
    'Khotang': 'khotang',
    'Morang': 'morang',
    'Okhaldhunga': 'okhaldhunga',
    'Panchthar': 'panchthar',
    'Sankhuwasabha': 'sankhuwasabha',
    'Solukhumbu': 'solukhumbu',
    'Sunsari': 'sunsari',
    'Taplejung': 'taplejung',
    'Tehrathum': 'tehrathum',
    'Udayapur': 'udayapur',

    // Madhesh
    'Bara': 'bara',
    'Dhanusha': 'dhanusha',
    'Mahottari': 'mahottari',
    'Parsa': 'parsa',
    'Rautahat': 'rautahat',
    'Saptari': 'saptari',
    'Sarlahi': 'sarlahi',
    'Siraha': 'siraha',

    // Bagmati
    'Bhaktapur': 'bhaktapur',
    'Chitwan': 'chitwan',
    'Dhading': 'dhading',
    'Dolakha': 'dolakha',
    'Kathmandu': 'kathmandu',
    'Kavrepalanchok': 'kavrepalanchok',
    'Lalitpur': 'lalitpur',
    'Makwanpur': 'makwanpur',
    'Nuwakot': 'nuwakot',
    'Ramechhap': 'ramechhap',
    'Rasuwa': 'rasuwa',
    'Sindhuli': 'sindhuli',
    'Sindhupalchok': 'sindhupalchok',

    // Gandaki
    'Baglung': 'baglung',
    'Gorkha': 'gorkha',
    'Kaski': 'kaski',
    'Lamjung': 'lamjung',
    'Manang': 'manang',
    'Mustang': 'mustang',
    'Myagdi': 'myagdi',
    'Nawalpur': 'nawalpur',
    'Parbat': 'parbat',
    'Syangja': 'syangja',
    'Tanahun': 'tanahun',

    // Lumbini
    'Arghakhanchi': 'arghakhanchi',
    'Banke': 'banke',
    'Bardiya': 'bardiya',
    'Dang': 'dang',
    'Gulmi': 'gulmi',
    'Kapilvastu': 'kapilvastu',
    'Parasi': 'parasi',
    'Palpa': 'palpa',
    'Pyuthan': 'pyuthan',
    'Rolpa': 'rolpa',
    'Rukum East': 'rukum_east',
    'Rupandehi': 'rupandehi',

    // Karnali
    'Dailekh': 'dailekh',
    'Dolpa': 'dolpa',
    'Humla': 'humla',
    'Jajarkot': 'jajarkot',
    'Jumla': 'jumla',
    'Kalikot': 'kalikot',
    'Mugu': 'mugu',
    'Rukum West': 'rukum_west',
    'Salyan': 'salyan',
    'Surkhet': 'surkhet',

    // Sudurpashchim
    'Achham': 'achham',
    'Baitadi': 'baitadi',
    'Bajhang': 'bajhang',
    'Bajura': 'bajura',
    'Dadeldhura': 'dadeldhura',
    'Darchula': 'darchula',
    'Doti': 'doti',
    'Kailali': 'kailali',
    'Kanchanpur': 'kanchanpur',
  };
}