// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7OFJm-Jdgzv3lzZ4QguDsAZTzV8zXbw',
    appId: '1:835851472767:web:98a64d2e0153fc8fa6944a',
    messagingSenderId: '835851472767',
    projectId: 'nibangsh-ubt-app-41372',
    authDomain: 'nibangsh-ubt-app-41372.firebaseapp.com',
    storageBucket: 'nibangsh-ubt-app-41372.firebasestorage.app',
    measurementId: 'G-P9PC0NPV5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC654-duXbzXPE1h8AhyQnwPXVffJVl8JE',
    appId: '1:835851472767:android:9fd532dd892fcbaca6944a',
    messagingSenderId: '835851472767',
    projectId: 'nibangsh-ubt-app-41372',
    storageBucket: 'nibangsh-ubt-app-41372.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApz9Ul-g45B5nPphAsK_95IFZvByBIvG0',
    appId: '1:835851472767:ios:a208737bbd3ad663a6944a',
    messagingSenderId: '835851472767',
    projectId: 'nibangsh-ubt-app-41372',
    storageBucket: 'nibangsh-ubt-app-41372.firebasestorage.app',
    iosBundleId: 'com.example.nibangshConsultancy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApz9Ul-g45B5nPphAsK_95IFZvByBIvG0',
    appId: '1:835851472767:ios:a208737bbd3ad663a6944a',
    messagingSenderId: '835851472767',
    projectId: 'nibangsh-ubt-app-41372',
    storageBucket: 'nibangsh-ubt-app-41372.firebasestorage.app',
    iosBundleId: 'com.example.nibangshConsultancy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7OFJm-Jdgzv3lzZ4QguDsAZTzV8zXbw',
    appId: '1:835851472767:web:688db547c2dbe9a0a6944a',
    messagingSenderId: '835851472767',
    projectId: 'nibangsh-ubt-app-41372',
    authDomain: 'nibangsh-ubt-app-41372.firebaseapp.com',
    storageBucket: 'nibangsh-ubt-app-41372.firebasestorage.app',
    measurementId: 'G-WM3L73P5JJ',
  );
}
